@baseUrl = http://127.0.0.1:3002/api
@token=c3f71b8a-1596-4990-a595-9f64c08c6e2a
### Récupérer la valeur setup-token
{{baseUrl}}/session/properties
Content-Type: application/json

### Créer l'administrateur
# token = setup-token
# Récupérer l'id de session
POST {{baseUrl}}/setup
Content-Type: application/json

{
  "token":"{{token}}",
  "user": {
    "first_name":"Emmanuel",
    "last_name":"Medina",
    "site_name":"IUT",
    "email":"emmanuel.medina@univ-lorraine.fr",
    "password":"supermotdep@ss3",
    "password_confirm":"supermotdep@ss3"
  },
  "prefs": {
    "site_name":"IUT",
    "site_locale":"fr"
  }
}


### Ajouter la base de données
# X-Metabase-Session = id
POST {{baseUrl}}/database
Content-Type: application/json
X-Metabase-Session: 12507a99-bdee-4e3a-8897-66e7761c0951

{
  "engine":"postgres",
  "name":"northwind",
  "is_on_demand":false,
  "is_full_sync":true,
  "is_sample":false,
  "cache_ttl":null,
  "refingerprint":false,
  "auto_run_queries":true,
  "schedules":{},
  "details":{
    "host":"postgresql",
    "port":null,
    "dbname":"northwind",
    "user":"postgres",
    "password":"supermotdepasse",
    "ssl":false,
    "tunnel-enabled":false,
    "advanced-options":false
  }
}



### Liste des base de données
GET {{baseUrl}}/database
Content-Type: application/json
X-Metabase-Session: ce635e7a-4815-494b-aec4-345ea177ebd3
