@baseUrl = http://127.0.0.1:3003/rest

POST {{baseUrl}}/owner/setup
Content-Type: application/json

{
  "email":"emmanuel.medina@univ-lorraine.fr",
  "firstName":"Emmanuel",
  "lastName":"Medina",
  "password":"Supermotdepass3"
}
