@baseUrl = http://127.0.0.1:3006

OPTIONS  {{baseUrl}}/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

###
POST {{baseUrl}}/graphql
Content-Type: application/graphql

query MyQuery {
  query {
    allEmployes {
      nodes {
        nom
        poste
        salaire
      }
    }
  }
}
