apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    url: mariadb:3306
    user: root
    jsonData:
      database: northwind
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
    secureJsonData:
      password: ${DB_ROOT_PASSWORD}
