apiVersion: 1

datasources:
  - name: Northwind
    type: postgres
    url: postgresql:5432
    user: postgres
    secureJsonData:
      password: ${DB_ROOT_PASSWORD}
    jsonData:
      database: northwind
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 10 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false
