apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    orgId: 1
    isDefault: true
    access: proxy
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.50.0

# http://localhost/grafana/api/datasources
