### Est ce que Loki est prêt ?
GET http://localhost:3100/ready

### Log Level ?
GET http://localhost:3100/log_level

### Metrics
GET http://localhost:3100/metrics

### Patterns
GET http://localhost:3100/loki/api/v1/patterns

###
### https://grafana.com/docs/loki/latest/reference/loki-http-api/#ingest-logs
POST http://localhost:3100/loki/api/v1/push
Content-Type: application/json

{
  "streams": [
    {
      "stream": { "label": "value" },
      "values": [
          [ "1730727694000000000", "<log line>" ],
          [ "1730727700000000000", "Demo message" ]
      ]
    }
  ]
}
