\c ventdest

alter table products
  alter column product_id
  add generated by default as identity;

alter table orders
  alter column order_id
  add generated by default as identity;

/*
alter table tiers
  alter column tiers_id
  add generated by default as identity;

select setval(pg_get_serial_sequence('tiers', 'tiers_id'), max(tiers_id))
from tiers;
*/

alter table shippers
  alter column shipper_id
  add generated by default as identity;

select setval(pg_get_serial_sequence('shippers', 'shipper_id'), MAX(shipper_id))
from shippers;
