\c northwind

alter table products  
  alter column product_id 
  add generated by default as identity;

alter table orders
  alter column order_id 
  add generated by default as identity;

alter table fournisseurs
  alter column fournisseur_id 
  add generated by default as identity;

SELECT setval(pg_get_serial_sequence('fournisseurs', 'fournisseur_id'), MAX(fournisseur_id)) 
FROM fournisseurs;

alter table shippers
  alter column shipper_id 
  add generated by default as identity;

SELECT setval(pg_get_serial_sequence('shippers', 'shipper_id'), MAX(shipper_id)) 
FROM shippers;
