\c northwind

alter table products  
  alter column product_id 
  add generated by default as identity;

--SELECT setval(pg_get_serial_sequence('products', 'product_id'), MAX(product_id)) FROM products;

alter table orders
  alter column order_id 
  add generated by default as identity;
