\c ventdest

create table vols (
  jour date,
  operateur_code_iata text,
  vol_numero int,
  appareil_code text,
  origine text,
  destination text,
  distance int,
  fuseau_horaire_origine text,
  fuseau_horaire_destination text,
  heure_prevue_depart timestamp with time zone null,
  delais_depart int,
  heure_depart timestamp with time zone null,
  roulage_depart int,
  decollage timestamp with time zone null,
  duree_vol int,
  atterrissage timestamp with time zone null,
  roulage_arrivee int,
  heure_arrivee timestamp with time zone null,
  delais_arrivee int,
  heure_prevue_arrivee timestamp with time zone null,
  duree_prevue int,
  duree int,
  derouté int, 
  annulé int,
  annulation_raison text,
  delais_du_control_aerien int,
  delais_du_securite int,
  delais_du_operateur int, 
  delais_du_avion int,
  delais_du_meteo int  
);
