\c ventdest

create index on cinema.salles 
  using btree (etablissement_id);

alter table cinema.salles 
  alter column salle_id 
    add generated by default as identity (
      sequence name salle_id_seq
      start with 1
      increment by 1
      no minvalue
      no maxvalue
      cache 1
    );

alter table cinema.seances 
  alter column seance_id 
    add generated by default as identity (
      sequence name seance_id_seq
      start with 1
      increment by 1
      no minvalue
      no maxvalue
      cache 1
    );

create index on cinema.seances 
  using btree (film_id);

create index on cinema.seances 
  using btree (salle_id);
